### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by verygreenboi** [Wrdlbrnft/Searchable-RecyclerView-Demo#1]
When I try to delete text from the searchView, it throws a IndexOutOfBoundsException.

**Comment by Wrdlbrnft** [comment]
Please post a Stacktrace of the exception and provide more information about the error. 

 - Are you using this repository as is without any modifications of your own?  
 - If you did change something than what did you change? 
 - And if you din't change anything than what device are you using? 
 - What version of Android are you using?

**Comment by verygreenboi** [comment]
Stacktrace
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: net.glassstones.bambammusic.debug, PID: 12858
                                                                                   java.lang.IndexOutOfBoundsException: Invalid index 16, size is 15
                                                                                       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                       at java.util.ArrayList.add(ArrayList.java:147)
                                                                                       at net.glassstones.bambammusic.ui.adapters.LocalTunesAdapter.moveItem(LocalTunesAdapter.java:95)
                                                                                       at net.glassstones.bambammusic.ui.adapters.LocalTunesAdapter.applyAndAnimateMovedItems(LocalTunesAdapter.java:77)
                                                                                       at net.glassstones.bambammusic.ui.adapters.LocalTunesAdapter.animateTo(LocalTunesAdapter.java:51)
                                                                                       at net.glassstones.bambammusic.ui.fragments.LocalTuneList.onQueryTextChange(LocalTuneList.java:103)
                                                                                       at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1148)
                                                                                       at android.support.v7.widget.SearchView.access$2000(SearchView.java:101)
                                                                                       at android.support.v7.widget.SearchView$12.onTextChanged(SearchView.java:1622)
                                                                                       at android.widget.TextView.sendOnTextChanged(TextView.java:7678)
                                                                                       at android.widget.TextView.handleTextChanged(TextView.java:7740)
                                                                                       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:9481)
                                                                                       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:975)
                                                                                       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
                                                                                       at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:215)
                                                                                       at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:30)
                                                                                       at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:245)
                                                                                       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:382)
                                                                                       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                       at android.os.Looper.loop(Looper.java:193)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5368)
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                                                       at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Wrdlbrnft** [comment]
You modified the repository. Are you sure that the the issue lies with my repository and not just with your modifications? My original repository works perfectly.

**Comment by janswist** [comment]
I have the same error - only when I delete chars from query. Only thing I modified is ExampleModel (I just use custom object model) and rest comes from repo. I'm getting it on Moto G 1 gen. I don't post stack trace since I have basically the same as `verygreenboi`'s and in the same circumstances.

**Comment by yitz-grocerkey** [comment]
It happens to me too, anytime the item inserted is the last item on the list. For example. List has 10 elements ([0] - [9]) and inserting an item at the 11th position ( [10]). ArrayList throws IndexOutOfBoundsException exception.

**Comment by hatpick** [comment]
I have this happening too, any solution?

**Comment by Wrdlbrnft** [comment]
The exact same issue? Then you are not using the up to date source code, but an older version? Please describe your problem in more detail, otherwise I can't give you any advice.

**Comment by hatpick** [comment]
Hi,

Sorry, yes I'm using the legacy code with triple functions for Add/Remove/Move items while filtering is being done. I fixed it myself, thanks.

**Comment by Wrdlbrnft** [comment]
@hatpick You should really update to the newest version...
