### ISSUE TITLE
throwIndexOutOfBoundsException

### ISSUE THREAD

**Issue by alphasil** [Wrdlbrnft/Searchable-RecyclerView-Demo#5]
Hi

I have the same issue with this code.

The line where the code throws is the following

```
public void addItem(int position, Atividades model) {
        atividadesList.add(position, model);
        notifyItemInserted(position);
    }
```
The log

03-10 21:46:31.282 16422-16422/com.gilca.ebspma E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.gilca.ebspma, PID: 16422
                                                                  java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                      at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                      at java.util.ArrayList.remove(ArrayList.java:403)
                                                                      at adapter.AtividadesCardViewAdapter.addItem(AtividadesCardViewAdapter.java:87)
                                                                      at adapter.AtividadesCardViewAdapter.applyAndAnimateAdditions(AtividadesCardViewAdapter.java:65)
                                                                      at adapter.AtividadesCardViewAdapter.animateTo(AtividadesCardViewAdapter.java:48)
                                                                      at fragments.AtividadesRecFragment$3.onQueryTextChange(AtividadesRecFragment.java:124)
                                                                      at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1150)
                                                                      at android.support.v7.widget.SearchView.access$2000(SearchView.java:103)
                                                                      at android.support.v7.widget.SearchView$12.onTextChanged(SearchView.java:1665)
                                                                      at android.widget.TextView.sendOnTextChanged(TextView.java:8599)
                                                                      at android.widget.TextView.handleTextChanged(TextView.java:8681)
                                                                      at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10897)
                                                                      at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:968)
                                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:519)
                                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:456)
                                                                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
                                                                      at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:691)
                                                                      at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:447)
                                                                      at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
                                                                      at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5832)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Any solution?

**Comment by henriquedesousa** [comment]
Looking at the stacktrace, I'd say you're doing something very wrong, instead of a problem in the original code: if you just added an item, how come the size of the list is 0? :)

**Comment by alphasil** [comment]
It seems i'm not the only one with this issue but i resolved it adding this to the function
`public boolean onQueryTextChange(String newText) {
                if(newText.equals("")) {
                    return false;
                }
                else {
                    final List<Atividades> filteredModelList = filter(listItemsList, newText);
                    adapter.animateTo(filteredModelList);
                    mRecyclerView.scrollToPosition(0);
                    return true;
                }
            }`

So, if there is no string to query...it simply return false and the error is gone

**Comment by henriquedesousa** [comment]
Just comenting out, but, when the filter is empty after a previous non-empty query, it means the entire list should be recreated, right?

**Comment by alphasil** [comment]
Yes it does....with return false the original list is recreated.

**Comment by yitz-grocerkey** [comment]
please see #1
